spring.application.name=${CATALOG_SERVICE_APP_NAME:catalog-service}
server.port=${CATALOG_SERVICE_APP_PORT:8071}

#Actuator
management.info.git.mode=full
management.endpoints.web.exposure.include=health,info

#Datasource
spring.datasource.url=${CATALOG_DB_URL:jdbc:postgresql://localhost:15432/catalog_db}
spring.datasource.username=${CATALOG_DB_USER:sujay}
spring.datasource.password=${CATALOG_DB_PWD}

#Spring JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

#App related
catalog.page-size=10
