spring.application.name=catalog-service
server.port=8071

management.info.git.mode=full
management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://localhost:15432/catalog_db
spring.datasource.username=sujay
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
