# SQL itself
logging.level.org.hibernate.SQL=DEBUG

# Parameter binding (Hibernate 6+)
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.orm.jdbc.extract=TRACE

logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"