spring.application.name=${CATALOG_SERVICE_APP_NAME:catalog-service}
server.port=8081

#Actuator
management.info.git.mode=full
management.endpoints.web.exposure.include=health,info

#Datasource
spring.datasource.url=${CATALOG_DB_URL:jdbc:postgresql://localhost:15432/catalog_db}
spring.datasource.username=${CATALOG_DB_USER:sujay}
spring.datasource.password=${CATALOG_DB_PWD}

#Spring JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

#App related
catalog.page-size=10

#logging
logging.level.dev.jeppu=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.orm.jdbc.extract=TRACE


